import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import GlobalUserButton from "@/components/GlobalUserButton";
import ToastProvider from "@/components/ToastProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className="antialiased"
        >
          <ToastProvider>
            <GlobalUserButton />
            {children}
          </ToastProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
